version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: teste3
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  node-app:
    build:
      context: .  
    container_name: node-app
    volumes:
      - .:/app  
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy 
    networks:
      - app-network
    command: ["npm", "start"] 
networks:
  app-network:
    driver: bridge
